from layers.Interactor.route.route_load_all_news import RouteLoadAllNews
from layers.Interactor.route.route_add_news import RouteAddNews
from layers.Interactor.route.route_load_news import RouteLoadNews