from modules.module_auth.routes.view_register_user import ViewRegisterUser
from modules.module_auth.routes.view_login_user import ViewLoginUser
from modules.module_auth.routes.view_logout_user import ViewLogoutUser
